# Generated by Django 2.0.4 on 2018-04-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_product_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='media/images/image.jpg', upload_to='media/images/'),
        ),
    ]
