# Generated by Django 2.0.4 on 2018-04-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='static/images/products/image.jpg', upload_to='static/images/products'),
        ),
    ]
